@del dscr_dw.LST
@del dscr_dw.OBJ
@del dscr_te.LST
@del dscr_te.OBJ
@del fw.LST
@del fw.OBJ
@del i2c.LST
@del i2c.OBJ
@del spi.LST
@del spi.OBJ
@del te_api.LST
@del te_api.OBJ
@del usb_dw
@del usb_dw.bin
@del usb_dw.hex
@del usb_dw.iic
@del usb_dw.M51
@del usb_te
@del usb_te.bin
@del usb_te.hex
@del usb_te.iic
@del usb_te.M51
@del versions.LST
@del versions.OBJ
